### ISSUE TITLE
Option to not plan dependent modules

### ISSUE THREAD

**Issue by jghward** [transcend-io/terragrunt-atlantis-config#101]
Thanks for this awesome tool!

For my setup it's not particularly useful to have Atlantis plan all dependent modules when I make a change to a parent module. Since the outputs of the parent module won't change until I run a `refresh` or `apply` there, there won't be any impact on child module plans.

For that reason, it would be great to have an `--ignore-dependencies` flag or similar (but still respecting manually added dependencies via the `extra_atlantis_dependencies` local var.)

**Comment by dmattia** [comment]
Thanks for opening up the issue!

Just to be clear, you would like Atlantis to _only_ use dependencies specified in `extra_atlantis_dependencies`, and not using source terraform modules, `dependency` blocks, etc.?

It might be possible to have modular flags where you could turn off/on each different source of dependencies

**Comment by jghward** [comment]
For my specific use-case I just want to be able to ignore the `dependency` blocks - so the `when_modified` field for projects in the generated Atlantis config would still include `*.hcl` and `*.tf`, and anything I've specified in `extra_atlantis_dependencies`, but not the `terragrunt.hcl` files of `dependency` modules.

**Comment by evanstoddard23** [comment]
Would there be a way to ignore dependencies for plans where, as you mentioned, downstream dependencies aren't affected until the parent is applied, but not ignore dependencies for applies?
