### ISSUE TITLE
Update the terragrunt Go module to 0.23.32

### ISSUE THREAD

**Issue by jeromepin** [transcend-io/terragrunt-atlantis-config#102]
Until [0.23.32](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.32), a bug in terragrunt [prevent the use of `dependency`](https://github.com/gruntwork-io/terragrunt/issues/992) in Terragrunt's hooks.

That way, when parsing a terragrunt.hcl file with `terragrunt-atlantis-config` it fails with `Unknown variable; There is no variable named "dependency".`.

A sample terragrunt.hcl may be :

```hcl
dependency "kubernetes" {
  config_path = "${get_parent_terragrunt_dir()}/kubernetes"
}

terraform {
  before_hook "local-admin" {
    commands = ["plan", "apply"]
    execute = ["az", "aks", "get-credentials", dependency.kubernetes.outputs.foo, REDACTED]
  }
  source = "${local.git_root}/modules/terragrunt/aks"
}
```

Can you consider to update its version to at least 0.23.32 ?

Thanks a lot ! 😃

**Comment by tx-kstav** [comment]
@jeromepin is the terraform block you initaly posted working for you now? I'm getting the same error with atlantis-terragrunt-config 1.6.0, Terragrunt v0.28.18, and Terraform v0.14.9

**Comment by jeromepin** [comment]
@tx-kstav I think the first block works now. But the following doesn't with the error `Error: terragrunt.hcl:103,18-28: Unknown variable; There is no variable named "dependency".`

```hcl
  98   │   before_hook "before_hook" {
  99   │     commands = ["apply", "plan", "destroy", "refresh", "import"]
 100   │     execute = [
 101   │       "python",
 102   │       "script.py",
 103   │       "https://${dependency.kubernetes.outputs.gke.cluster_endpoint}",
 104   │       dependency.kubernetes.outputs.gke.cluster_ca_cert,
 105   │     ]
 106   │   }
```

**Comment by dmattia** [comment]
@tx-kstav yes please!

**Comment by jeromepin** [comment]
@tx-kstav Can you please ping me once you opened it ? I'm interested in following the issue.
