### ISSUE TITLE
Feature Request: custom when_modified flag

### ISSUE THREAD

**Issue by devlincashman** [transcend-io/terragrunt-atlantis-config#126]
Had a use case recently where it would be nice to trigger planning based off of *.pkr.hcl files in a given directory. But there is not currently a --when-modified *.pkr.hcl type flag to define custom when_modified rules. Would be nice to generate these with terragrunt-atlantis-config and pre workflow hooks.

**Comment by dmattia** [comment]
I do the same in the monorepo I built this package for and use the `extra_atlantis_dependencies` locals fields to define these.

So If I have an `foo/ami/main.pkr.hcl` file and a `foo/instance/terragrunt.hcl` module that you want to apply anytime the `ami/main.pkr.hcl` file changes, you can just add:

```hcl
locals {
  extra_atlantis_dependencies = ["../ami"]
}
```

to your terragrunt file and everything should work for you.

I don't believe this could be accomplished using a CLI flag, as there is no easy way to tell which packer files belong to which infrastructure files.

If you want this to work automatically, you could use an `extra_atlantis_dependencies` value in your parent terragrunt directory that your child modules inherit from.

I'll close this for now, but please feel free to re-open if you have any other questions or if this does not work for your use case

**Comment by devlincashman** [comment]
Great idea! Thank you.
