### ISSUE TITLE
No binary builds for 1.2.1

### ISSUE THREAD

**Issue by pmichna** [transcend-io/terragrunt-atlantis-config#127]
There are no binary builds for release [v1.2.1](https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v1.2.1). Only source code is available in the "Assets" section.

**Comment by dmattia** [comment]
Good catch, updated now: https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v1.2.1
