### ISSUE TITLE
Set empty `apply_requirements`

### ISSUE THREAD

**Issue by pmichna** [transcend-io/terragrunt-atlantis-config#128]
I want to set `apply_requirements: []` in `atlantis.yaml` for some of my projects (overriding default server-side config). I've tried setting the following in `terragrunt.hcl`.

```
locals {
  atlantis_apply_requirements = []
}
```

However, `terragrunt-atlantis-config` does not generate any `apply_requirements` in this case. Is it possible with the newest terragrunt-atlantis-config?

**Comment by dmattia** [comment]
This is not currently possible, as this line https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/cmd/config.go#L53 says to omit the apply requirements if the list is empty. I can add this as a feature request though.

**Comment by pmichna** [comment]
Yes, adding this as a feature request is great. Thanks!

**Comment by dmattia** [comment]
This was released in https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v1.3.0

**Comment by pmichna** [comment]
Thanks for releasing new code so quickly!

Do I understand correctly that now if I don't specify any `atlantis_apply_requirements` in a `locals` block in `terragrunt.hcl`, the project in the resulting atlantis config has `apply_requirements: []`? If yes, then I think it is not helpful.

Example:
1. server config has `apply_requirements: [approved, mergeable]`
2. there is no `locals` block in `terragrunt.hcl`
3. the resulting project from `terragrunt-atlantis-config` has `apply_requirements: []` which overrides the server config although I have not wanted that.

Am I missing something? What I originally expected was to include `apply_requirements: []` only if explicitly defined in `terragrunt.hcl`. If not defined in `terragrunt.hcl` - do not define it in the ouput (`atlantis.yaml`).

**Comment by dmattia** [comment]
That makes sense, I just opened https://github.com/transcend-io/terragrunt-atlantis-config/pull/130 which will only put `apply_requirements: []` in the output if the empty list was specified in a locals block.

To see the new expected output, check out the `cmd/golden/apply_overrides.yaml` file, which shows the expected output of the `test_examples/apply_requirements_overrides/` directory.

The tests are passing here: https://app.circleci.com/pipelines/github/transcend-io/terragrunt-atlantis-config/320/workflows/ef75e87a-780b-46b1-86ff-e1813847a1c8
