### ISSUE TITLE
An argument named "working_dir" is not expected here

### ISSUE THREAD

**Issue by chkelly** [transcend-io/terragrunt-atlantis-config#131]
We are leveraging the working_dir argument in our terragrunt.hcl which was recently added https://github.com/gruntwork-io/terragrunt/pull/1584 and https://github.com/gruntwork-io/terragrunt/pull/1588

atlantis.yaml file generation is failing however with:

```
$ terragrunt-atlantis-config generate --ignore-parent-terragrunt --autoplan --output atlantis.yaml --parallel=false --workflow terragrunt --create-project-name --automerge
INFO[0000] Could not find an old config file. Starting from scratch
Error: ${REPO_ROOT}/terragrunt.hcl:51,5-16: Unsupported argument; An argument named "working_dir" is not expected here.
```

We have an after hook that cleans up the terragrunt-cache 
```
terraform {
  after_hook "cleanup_cache" {
    commands    = local.is_atlantis == true ? ["apply"] : ["plan"]
    working_dir = get_terragrunt_dir()
    execute     = ["rm", "-rf", "./.terragrunt-cache"]
  }
}
```

I'll submit a PR in a minute to bump the version of terragrunt which appears to resolve this issue.

**Comment by dmattia** [comment]
This should be fixed and released in https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v1.4.1, thank you for your PR!

**Comment by chkelly** [comment]
Thanks for the cutting a release so quickly!
