### ISSUE TITLE
Binary file not working in custom Docker image

### ISSUE THREAD

**Issue by enarmontas** [transcend-io/terragrunt-atlantis-config#137]
I am using base `runatlantis/atlantis` image and adding `terragrunt-atlantis-config` with this command in my Dockerfile:
```
RUN curl -LfsSo terragrunt-atlantis-config_1.4.1_linux_amd64.tar.gz https://github.com/transcend-io/terragrunt-atlantis-config/releases/download/v1.4.1/terragrunt-atlantis-config_1.4.1_linux_amd64.tar.gz && \
  tar -xf terragrunt-atlantis-config_1.4.1_linux_amd64.tar.gz && \
  mv terragrunt-atlantis-config_1.4.1_linux_amd64/terragrunt-atlantis-config_1.4.1_linux_amd64 /usr/local/bin/terragrunt-atlantis-config 
```

When I try to run it, I get `No such file or directory` error. Here is an example:
```
bash-5.0# cd /usr/local/bin/ 
bash-5.0# ls -la 
... 
-rwxr-xr-x 1 root root 32634795 Apr 22 11:03 terragrunt 
-rwxr-xr-x 1 root root 34364386 Apr 22 11:03 terragrunt-atlantis-config
```
Run `terragrunt-atlantis-config`: 
```
bash-5.0# terragrunt-atlantis-config version 
bash: /usr/local/bin/terragrunt-atlantis-config: No such file or directory 
```
However, `terragrunt` works fine:
```
bash-5.0# terragrunt -v 
terragrunt version v0.28.21 
```

I can see that `terragrunt` is statically linked, but `terragrunt-atlantis-config` is linked dynamically:
```
bash-5.0# file terragrunt
terragrunt: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=YSXQP524fiAkFMKe2U4_/S0q5UyF0QhZgFWUrYiP2/Sqqd1PtyS4TlTRI0UNHe/XD0BQokFh98OO6OVteVr, not stripped
```

```
bash-5.0# file terragrunt-atlantis-config
terragrunt-atlantis-config: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=7EL3iPQXP4fCVdoenZYY/2GjvWCEb3f3_v_C09Tv9/CAJ2SWTEjAu_pe4NCLVc/4y26e-1R_sjIUBXB2jGx, not stripped
```
I guess I need some prerequisites to run `terragrunt-atlantis-config` this way?

**Comment by dmattia** [comment]
My initial gut reaction is that using `mv` to `/usr/local/bin/` may not be correct here, as there are possibly some permissions issues going on.

Instead, could you try to use the `install` command like `sudo install terragrunt-atlantis-config /usr/local/bin` to ensure that the permissions are properly setup? This is how I install it on my docker image (see: https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/README.md#integrate-into-your-atlantis-server)

Please let me know if this does or does not solve your issue 😄

**Comment by enarmontas** [comment]
Same issue, I have used this one now:

```
RUN wget https://github.com/transcend-io/terragrunt-atlantis-config/releases/download/v1.5.0/terragrunt-atlantis-config_1.5.0_linux_amd64.tar.gz && \
  tar xf terragrunt-atlantis-config_1.5.0_linux_amd64.tar.gz && \
  mv terragrunt-atlantis-config_1.5.0_linux_amd64/terragrunt-atlantis-config_1.5.0_linux_amd64 terragrunt-atlantis-config && \
  install terragrunt-atlantis-config /usr/local/bin
```

I'll try to build go package myself and will let you know if that changes anything.

**Comment by enarmontas** [comment]
I was able to find the issue. Atlantis is based on Alpine image, which doesn't have compatibility libraries for `glibc` by default. I have added an extra step to my Dockerfile and now it works:
```
RUN apk add --no-cache libc6-compat
```

Is there any reason why `terragrunt-atlantis-config` is built dynamically vs statically?

**Comment by dmattia** [comment]
Ah, classic Alpine. Great catch @enarmontas!

Being honest I'm not too familiar with dynamic vs static binaries and what the pros/cons might be. If being statically built we be an improvement, an issue would definitely be welcome with a bit of background on what that would help with.

If you're curious about our current release pipeline for builds, this library:
- defines a goxc config here: https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/.goxc.json
- Has a Makefile rule to call goxc via `make build-all` defined here: https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/Makefile#L25-L32
- Has a Github Actions workflow that on releases will call that Makefile rule and upload the files to our release: https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/.github/workflows/release.yml#L33-L45

It's a pretty simple setup, so hopefully changing parts of it won't be too complicated.

**Comment by jeenx** [comment]
+1 I also got bit my this, I found it odd there is a dependency outside the Go binary
