### ISSUE TITLE
Sorting order changed with the 1.6 release

### ISSUE THREAD

**Issue by languitar** [transcend-io/terragrunt-atlantis-config#143]
With the recently release version 1.6.0 of this project, our whole `atlantis.yaml` would be re-ordered, resulting in a huge diff without any actual changes. Is this intended?

**Comment by dmattia** [comment]
Yes it is. Before https://github.com/transcend-io/terragrunt-atlantis-config/pull/141 merged, the possible order was not consistent (and would possibly differ based on a race condition), but it should be consistent now. I also experienced having my diffs never change from running `generate` in the past, but now we can be sure that the future ordering will be consistent.

Thanks for opening!
