### ISSUE TITLE
Provide checksums for GitHub release assets

### ISSUE THREAD

**Issue by bmbferreira** [transcend-io/terragrunt-atlantis-config#149]
Please provide some way to obtain a checksum for the release assets, SHA256 for example. Thank you!

**Comment by dmattia** [comment]
My understanding is that the list tags (https://docs.github.com/en/rest/reference/repos#list-repository-tags) endpoint provides this functionality for Github releases. Does this work for your use case @bmbferreira?

**Comment by dmattia** [comment]
I now provide checksums (SHA256 and SHA512), starting with v1.7.2, as seen here: https://github.com/transcend-io/terragrunt-atlantis-config/releases

Does this cover your use case @bmbferreira?

**Comment by bmbferreira** [comment]
Yes thank you for the quick response! The endpoint you referred does not solve the issue: https://github.community/t/release-checksums-on-github/137764/6 😕

But I can see the checksums now on the release 👌 thank you! 🙇‍♂️
