### ISSUE TITLE
Feature Request: use arbitrary hcl files for Atlantis project generation

### ISSUE THREAD

**Issue by tafkam** [transcend-io/terragrunt-atlantis-config#151]
We are using a rather large and complex terragrunt repository with several arbitrary hcl files in the hierarchy (i.e. region.hcl, env.hcl, product.hcl, service.hcl, etc.) above the child terragrunt.hcl directories. Using Atlantis and terragrunt-atlantis-config right now would require us to manually "atlantis plan/apply" each terragrunt child in the order of the dependency graph, since Atlantis can't resolve project dependencies (e.g. https://github.com/runatlantis/atlantis/issues/391, https://github.com/runatlantis/atlantis/issues/972), and terragrunt-atlantis-config defines each terragrunt child as it's own project.

Since most of our regularly changing dependencies are inside of the product or service hierarchy, we would like to generate an atlantis.yaml on the directories containing those hcl files, and using "terragrunt run-all plan/apply" in the Atlantis workflow for all sub-directories to ensure all childs are applied in order with the refreshed outputs of their dependencies.

"External" Terragrunt dependencies outside of the directories with the specified hcl files should be aggregated for all terragrunt childs in their respective sub-folders, and be exposed for Atlantis in when_modified. Specifying multiple hcl files to generate Atlantis directories would give some flexibility what modules to deploy according to the scope of the pull-request.

This should significantly reduce manual footwork and ordering errors in large pull-requests, e.g. for updating terraform or terraform providers, large staging->prod promotions, and new products/tenants. 

This would result in just using "atlantis plan -p account_env_region_product" instead of planning and applying each of the product's 107 terragrunt childs. As far as I can tell this should be already possible with "atlantis plan -d account/env/region/product", but the auto-plan would still use the terragrunt child modules and not the whole product or service, or whatever floats your boat.

(Disclaimer: Our terragrunt project is pretty fresh, maybe I'm missing some critical points in the terraform/terragrunt/atlantis/terragrunt-atlantis-config ecosystem with this feature request ;-))

**Comment by dmattia** [comment]
This is certainly interesting. I also run terragrunt-atlantis-config in a fairly large repo (600 terragrunt modules or so) and don't love the UX of having all of those modules display, but I always found the output of `run-all plan` to be difficult to parse.

But maybe that's gotten better, as tbh I haven't kept up with the `-all` commands for quite a few terragrunt versions.

So I just want to make sure I understand your ideal flow here: would it just be the `run-all plan` output that appears when running `atlantis plan -p account_env_region_product`?

**Comment by tafkam** [comment]
Yes, pretty much. Right now we are using a nodejs output filter from some guy on github ;-) I guess making changes for run-all workflows in terragrunt_light.js are comparably small.

**Comment by dmattia** [comment]
That's very fair. How are you thinking you'd mark a directory as the root of a project?

**Comment by tafkam** [comment]
I would imagine a parameter like "--project-tgconfig-files=product.hcl,env.hcl" and a separate parameter like "--create-child-projects" (default true) to optionally turn off the creation of terragrunt child module projects.
