### ISSUE TITLE
Question: How to run terragrunt-atlantis-config to run atlantis with dependencies

### ISSUE THREAD

**Issue by konstantin-recurly** [transcend-io/terragrunt-atlantis-config#153]
We usually have 3 different cases of how we run terragrunt.

- a single resource
- two separate resources
- two resources where one of the resources has a dependency on another

The first two cases work as expected with no issues.

The last case doesn't work as we expect.
We have two resources that are located in different folders
```bash
.
├── bindings
│   └── terragrunt.hcl
└── service-accounts
    └── terragrunt.hcl
```

`bindings/terragrunt.hcl` has a dependency from service-account and we use `mock_outputs` in order to succeed the `atlantis plan`
```
  mock_outputs = {
    iam_email = "serviceAccount:dummy-service-account@${local.common.project_id}.iam.gserviceaccount.com"
  }
```

This is how we generate our atlantis.yaml
`terragrunt-atlantis-config generate --output atlantis.yaml --autoplan --parallel --create-workspace`

When we run `atlantis plan` all works as expected and `bindings/terragrunt.hcl` uses `mock_outputs` to succeed the plan.

When we run `atlantis apply` it applies changes simultaneously without order and the resource that has dependencies fails, because it doesn't get real outputs from the dependency resource. 

Do I use `terragrunt-atlantis-config` not in the right way to generate the config?

**Comment by dmattia** [comment]
Hello, and thanks for the Issue!

I've seen quite a few repos that chain many terragrunt modules on each other, and I think there are two general patterns:

1) Don't use `mock_outputs`. When you first run `atlantis plan`, the depended_on module will plan successfully, while the dependent module will display an error. Then you run `atlantis apply` which will apply only the depended_on module. Then a second round of `atlantis plan` and `atlantis apply` will succeed.
2) When you run a plan, run `atlantis plan <other_args>` to just plan and apply the depended_on module(s) first, and then run `atlantis plan` and `atlantis apply` for the final round.

Personally, I use the first option in a repo with hundreds of modules (our atlantis.yaml is >15k lines, so we have a lot of dependencies), and it works well for our needs. So long as you aren't afraid of plans failing for dependent modules, and are okay with a few rounds of plans/applies, I highly recommend it.

I'll close this Issue for now, but absolutely feel free to keep commenting or re-open this if you have other concerns.

**Comment by konstantin-recurly** [comment]
@dmattia thanks for answering the question. If you don't mind I would like to elaborate on this a little bit more. 
The first approach works but that involves too many manual steps to see the final result. 
Also, how does it work with CI/CD approach?
It looks like that we would need to implement some logic and checks in our pipeline to make sure that all were deployed.

Do you use any CI/CD systems to deploy/apply changes to your infrastructure?
How does it look like in your implementation? 

Sorry, that I am asking so many questions I just wasn't able to find any helpful information anywhere. All that exists is about pure terraform/terraform enterprise, etc.

**Comment by dmattia** [comment]
Atlantis is a CI/CD system, and I use it to continuously deploy all infra. You can use github status checks to ensure that the atlantis plan job always succeeds, and can see yourself that everything is up to date.

My workflow goes:
- Put up PR
- Run plan
- Wait for approval
- Run apply.
- Re-run plan and apply if necessary until all modules are applied
- merge

This ensures that when I merge, my changes are always 100% deployed.

As far as this being too many manual steps, my understanding is that this is necessary. You cannot both review each `atlantis plan` output as a human, while also deeply applying modules that depend on outputs that don't exist yet. The consensus of tools like Atlantis, Terraform Cloud, Pulumi Cloud, etc. is that the default should be that all plans should be manually approved, as infrastructure deploys carry very high risk (your new junior dev may not know that changing a database name will recreate the whole thing, losing data).

My recommendation is to embrace the manual steps as a part of your CD pipeline, but if you want something entirely automatic, you can:
- skip Atlantis and run a `terragrunt run-all apply` from the root of your repo on a basic CI job
- wait for something like https://github.com/transcend-io/terragrunt-atlantis-config/issues/151 to merge, where you could have proxy commands to run `run-all apply` of subsets of your infrastructure codebase

**Comment by konstantin-recurly** [comment]
@dmattia Thank you very much for explaining and sharing your thoughts and your workflow that really helps.
