### ISSUE TITLE
Failure when using labeled include blocks

### ISSUE THREAD

**Issue by henworth** [transcend-io/terragrunt-atlantis-config#166]
When running this against a `terragrunt.hcl` file that has a labeled `include` block, the program errors out with:

`Extraneous label for include; No labels are expected for include blocks.`

A labeled block is one like this:

```
include "root" {
  path = find_in_parent_folders()
}
```

The [Terragrunt docs](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#include) recommend labeling every include block. They also state that support for non-labeled blocks is currently deprecated and only supported to be backward compatible:

> You can have more than one include block, but each one must have a unique label. It is recommended to always label your include blocks. Bare includes (include block with no label - e.g., include {}) are currently supported for backward compatibility, but is deprecated usage and support may be removed in the future.

**Comment by henworth** [comment]
Looks like this is similar to #167, due to this being a newer feature of terragrunt.

**Comment by dmattia** [comment]
For sure, I have the tests passing locally with the latest version now, I just need to add a few more tests to cover the new terragrunt features and we should be good to go 😄

**Comment by dmattia** [comment]
This should be fixed in v1.9.0: https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v1.9.0

Please let me know if it's not 😄
