### ISSUE TITLE
atlantis.yaml config block for terragrunt with multiple includes in 1.9.2 is not getting generatated

### ISSUE THREAD

**Issue by quynhnhatnguyen** [transcend-io/terragrunt-atlantis-config#176]
Setup:
* Version: 1.9.2
* Terragrunt version: 0.35.4
* Terragrunt example (Note: we dont use `terraform` block, and only `include` block with name)
```
locals {
  extra_atlantis_dependencies = [
    "../../../../../modules/instance_templates/terragrunt.hcl"
  ]
}

include "root" {
  path = find_in_parent_folders()
}

include "template" {
  path = "../../../../../modules/instance_templates/terragrunt.hcl"
}
```

Observed behavior:
Generated `atlantis.yaml` does not have the block for the above directory. Thus, the directory does not have any desired config, such as autoplan etc.

Expected bahavior:
Generatate `atlantis.yaml` should have the block for the above directory.

Note:
It starts to work if I change the above terragrunt content to the below (removing one of the include block name):
```
locals {
  extra_atlantis_dependencies = [
    "../../../../../modules/instance_templates/terragrunt.hcl"
  ]
}

include {
  path = find_in_parent_folders()
}

include "template" {
  path = "../../../../../modules/instance_templates/terragrunt.hcl"
}
```

Maybe we are missing updating some logic in checking in a module is parent (https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/cmd/parse_hcl.go#L30) after adding supporting multiple includes?

**Comment by dmattia** [comment]
Great catch, and thank you!

I do think we'll need to update that function you linked, specifically in this check: https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/cmd/parse_hcl.go#L56-L59, to account for multiple include blocks being a good signal that a module is not a parent.

If you'd like to contribute please let me know, otherwise I would gladly fix this bug this upcoming Friday :)

**Comment by quynhnhatnguyen** [comment]
Hi @dmattia Thank you for the promptly confirmation!
We will look forward to your fixes.

**Comment by dmattia** [comment]
perfect, thanks for letting me know. Added to my schedule on the 12th to work on this

**Comment by barrydobson** [comment]
Hi, any progress on this issue?

**Comment by dmattia** [comment]
Hello, there is not yet, though I still have it on my radar. I typically work on this project on Fridays, but there have been a few more pressing issues recently. This should be gotten to in the next few weeks

**Comment by dmattia** [comment]
Released in https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v1.14.1
