### ISSUE TITLE
Handling dependencies in parallel apply

### ISSUE THREAD

**Issue by enarmontas** [transcend-io/terragrunt-atlantis-config#183]
I have two modules, where module B depends on module A.
- A: aws/iam-user/example-bucket-user
- B: aws/s3-bucket/example-bucket

Here is my config:
```
terragrunt-atlantis-config generate --output atlantis.yaml \
  --autoplan --workflow terragrunt --create-workspace --parallel
```

It will generate the following project structure:
1. dir: aws/iam-user/example-bucket-user, workspace: aws_iam-user_example-bucket-user
2. dir: aws/s3-bucket/example-bucket, workspace: aws_s3-bucket_example-bucket

Now, when I run `atlantis apply` it will immediately fail, because Atlantis treats those projects as separate ones. It will try to apply both plans in parallel, IAM user will be created, but S3 bucket will fail, because it depends on IAM user. 
However, if I apply both plans in the correct order with `atlantis apply -d aws/iam-user/example-bucket-user -w aws_iam-user_example-bucket-user` it will succeed.

My question is: How to make sure that `terragrunt-atlantis-config` doesn't create separate projects for resources that are dependencies in other projects, so all dependencies are contained in the same Atlantis project?

In this example, I would want to see just a single project, where dependencies are handled on the Terragrunt level:
1. dir: aws/s3-bucket/example-bucket workspace: aws_s3-bucket_example-bucket

```
time=2021-11-12T15:06:08Z level=info msg=Stack at /home/atlantis/.atlantis/repos/example/terragrunt-live/200/aws_s3-bucket_example-bucket/aws/s3-bucket/example-bucket:
  => Module /home/atlantis/.atlantis/repos/example/terragrunt-live/200/aws_s3-bucket_example-bucket/aws/s3-bucket/example-bucket (excluded: false, dependencies: [/home/atlantis/.atlantis/repos/example/terragrunt-live/200/aws_s3-bucket_example-bucket/aws/iam-user/example-bucket-user])
  => Module /home/atlantis/.atlantis/repos/example/terragrunt-live/200/aws_s3-bucket_example-bucket/aws/iam-user/example-bucket-user (excluded: false, dependencies: [])
```

Is anything like that possible with `terragrunt-atlantis-config`?

**Comment by dmattia** [comment]
Having "stages" of plans is not yet supported in Atlantis: https://github.com/runatlantis/atlantis/issues/972, so there is no way to say have module A apply first, then module B in a single "apply" step while treating them as separate projects.

But you do still have a few options:
- Run `plan` and `apply` stages twice in cases like this. This is what I've done for a few years now with about 1000 modules, and it's worked pretty well. As a general rule, we just run `apply` until the last `plan` comes up empty. Some plans/applys will fail in intermediate steps, but they will all pass in the end.
- If you know the dependencies well, you can use something like `atlantis apply -d aws/iam-user/example-bucket-user -w aws_iam-user_example-bucket-user` to ensure that the further down dependencies all have the values they need by the time you run `atlantis apply`
- You can use "projects" with this library, which allow you to combine a set of terragrunt workspaces into a single project that can be planned/applied using `run-all` and `plan-all` in terragrunt (or whatever the new versions of those commands are). The docs are here: https://github.com/transcend-io/terragrunt-atlantis-config#project-generation. Notably, this feature just launched in the latest version of this lib last week, and I don't know how many groups are using it in production yet. Though from the testing I've seen it looks good.

I'll close this for now, as I'm not sure if there are any other better options we could really have until Atlantis supports the multi-stage applies, but if you have other ideas feel free to re-open and I'd love to hear your thoughts 😄

**Comment by dmattia** [comment]
> how you run plan and apply until they comes empty?

If you have new modules A and B and B depends on A:
- during the first plan, module A will show a plan, but B will fail because A doesn't have outputs
- during the first apply, module A will deploy, and B will not because it had no plan
- during the second plan, module A will show no changes while B will plan
- during the second apply, module B will apply

> how you handle failures in the modules in such case?
One of the nice things about Atlantis is that it runs before a PR merges. If there is a failure, I fix the issue before merging

> Is there a way to run run-all command in the parent folder?
No, and I don't think there's a good way to do that from a UX perspective. My view is that https://github.com/runatlantis/atlantis/issues/972 would eliminate the desire for `run-all` support, though I'm always interested in others' opinions

**Comment by canidam** [comment]
Got it. Actually plan and apply in iterations or by the the specific module sounds a good solution for now. Thanks
