### ISSUE TITLE
filter argument to match multiple folders

### ISSUE THREAD

**Issue by seany89** [transcend-io/terragrunt-atlantis-config#184]
I am trying to use the ``--filter`` option to match multiple folders in a directory.

Seems the expansion of ``--filter`` command to use glob expression was introduced in #136

I would assume something like this would work ``"test/accounts/**/{folder1,folder2}"``
so in all accounts, I only want to match contents in folder1 and 2.
Is this possible?

**Comment by dmattia** [comment]
You should be able to do something like `test/accounts/*/folder[12]` in the glob. Anything that golang's `filepath.Glob` supports should work in that flag 👍
