### ISSUE TITLE
Change to root terragrunt.hcl file causes plan/errors

### ISSUE THREAD

**Issue by jmreicha** [transcend-io/terragrunt-atlantis-config#187]
When editing the root level terragrunt.hcl file I am seeing the following behavior - I would have expected the behavior of the `--ignore-parent-terragrunt` flag to skip over changes to these types of files by default? 
```
exit status 1: running terragrunt plan -no-color -out=$PLANFILE
time=2021-12-09T20:37:39Z level=error msg=Found remote_state settings in /home/atlantis/.atlantis/repos/repo/1/default/env/stage/terragrunt.hcl but no backend block in the Terraform code in /home/atlantis/.atlantis/repos/repo/1/default/env/stage/default/activation/prod. You must define a backend block (it can be empty!) in your Terraform code or your remote state settings will have no effect! It should look something like this:

terraform {
  backend "s3" {}
}


time=2021-12-09T20:37:39Z level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

Here is the (simplified) config for reference. Adding or removing a variable in the locals block causes this error to appear.

```
terraform {
  extra_arguments "no_color" {
    commands  = ["init"]
    arguments = ["-no-color"]
  }
}

locals {
  vars             = jsondecode(file("vars.json"))
  terragrunt_local = get_env("TERRAGRUNT_LOCAL", "false")
}

remote_state {
    backend = "s3"
    config = {
        encrypt = true
        bucket = "env-stage-terraform-state"
        key = "${path_relative_to_include()}/terraform.tfstate"
        region = "us-west-2"
        dynamodb_table = "terraform-locks"
    }
}

terraform_version_constraint = ">= 0.13"
```

Hopefully this is some oversight on my part or is something that is easy to fix.

**Comment by dmattia** [comment]
Could you provide an overview of the file structure and how you are changing that file?

If you could, please add your files that have the errors in a new PR to this directory: https://github.com/transcend-io/terragrunt-atlantis-config/tree/master/test_examples. Though if you'd prefer to not make a PR, a bit more explanation would be appreciated, as nothing jumps out from the current config

**Comment by jmreicha** [comment]
Sure thing, here's a simplified version. So basically when I do a change on only the root terragrunt.hcl file is when I see the change. The child files are working as expected, hopefully that was clear before but figured I'd mention it.

```
❯ tree
.
├── _global
│   ├── cloudtrail
│   │   └── terragrunt.hcl
├── terragrunt.hcl
├── us-east-1
│   └── _global
│       ├── kms-master-key
│       │   └── terragrunt.hcl
├── us-west-2
│   └── stage
│       ├── kms-master-key
│       │   └── terragrunt.hcl
│       └── storage
│           ├── logging-bucket
│           │   └── terragrunt.hcl
│           ├── logging-bucket-replication
│           │   └── terragrunt.hcl
│           └── replication-role
│               └── terragrunt.hcl
└── vars.json
```

I'll work on getting a PR set up to test.

**Comment by dmattia** [comment]
Thank you! From the looks of it, this tool should definitely handle that sort of file path, so whether it's a bug in this lib or something I can help you with with your config, either way I'll be glad to help once you post that example 😄

**Comment by jmreicha** [comment]
Sorry, I forgot about this one. I have been unable to reproduce.
