### ISSUE TITLE
Relative path support on Windows

### ISSUE THREAD

**Issue by Dogers** [transcend-io/terragrunt-atlantis-config#19]
This seems to be a Windows only issue, as running it on a Linux machine it works as expected.. :(

When running this tool on our existing atlantis terragrunt setup, it's producing a config file with full, hardcoded paths to each project, rather than the expected relative path to the repo from the root. I'm guessing this is possibly a \ vs / chomping issue so hoping for it to be an easy fix! :)

**Comment by dmattia** [comment]
Definitely, I was expecting this to come up eventually :)

I don't have a windows machine myself, but I believe I can get a good test working with CircleCI's windows executors: https://circleci.com/docs/2.0/executor-types/#using-the-windows-executor

I'll play around with this and see if I can reproduce the issue, then making a fix should be the easy part

**Comment by dmattia** [comment]
So I have a fix working with tests on a windows machine, but am wondering: Do you want the atlantis.yaml output to always use unix path separators, or do you want Window's separators?

I'm guessing that your use case is that you develop locally on windows, but are deploying to an Atlantis server on a unix system, but please let me know if that assumption is incorrect

**Comment by Dogers** [comment]
That's correct - most of us are on Windows with some on Mac, but Atlantis is a Linux container.

**Comment by dmattia** [comment]
@Dogers I closed this issue as the tests are passing on Windows executors, but my tests passing or only worth as much as the knowledge I baked in about Windows systems, which is not a ton.

If you have any issues (particularly with how I handled newlines), feel free to reopen!
