### ISSUE TITLE
Don't add default values to yaml

### ISSUE THREAD

**Issue by JoshiiSinfield** [transcend-io/terragrunt-atlantis-config#21]
Hi,

It seems that automerge & the autoplan are always output, even when default values.
Can the yaml be kept cleaner and not set them unless differing from the default?

``` Go
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
```

this autoplan config is the default, so isn't required everywhere. If dependencies are found then include just the when_modified...

Cheers,
Josh

**Comment by dmattia** [comment]
Thanks for the feature request! Is there a functional reason you don't want the automerge/autoplan values output, or is it aesthetic?

Right now we use https://github.com/ghodss/yaml for creating our YAML, which unfortunately doesn't appear super malleable for this kind of change, but I can see what I can do

**Comment by JoshiiSinfield** [comment]
Hi David,

it's purely aesthetic, so no worries if not. 

Cheers,
Josh

**Comment by dmattia** [comment]
I think I'll close this issue, as I'm not sure on an easy way to detect if the default values in the upstream atlantis repo were to change without adding an additional, large dependency.

But I may come back to this later
