### ISSUE TITLE
Unsupported argument; An argument named "mock_outputs_merge_strategy_with_state" is not expected here

### ISSUE THREAD

**Issue by m0ps** [transcend-io/terragrunt-atlantis-config#214]
_mock_outputs_merge_strategy_with_state_ was added in [v0.36.2](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.36.2)
https://github.com/gruntwork-io/terragrunt/pull/1936

**Comment by dmattia** [comment]
We'll need to bump https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/go.mod#L9

Feel free to open a PR, otherwise I can take this sometime soonish
