### ISSUE TITLE
Projects left without proper atlantis config on error

### ISSUE THREAD

**Issue by alk-jozog** [transcend-io/terragrunt-atlantis-config#232]
When terragrunt-atlantis-config fails (for instance on a terragrunt error in a project), we can end up in a situation where there is projects created but no `atlantis.yaml` file has been generated (I guess because it's generated at the end?).
When using it with atlantis's `pre_workflow_hooks`, this is an issue because Atlantis will proceed even if the hook has failed. Then instead of relying on `atlantis.yaml`, Atlantis will automatically parse projects, which can be misleading/broken because it doesnt have the proper associated config (for instance `atlantis_skip` is ignored).
As a workaround for now we create an empty `atlantis.yaml` before running terragrunt-atlantis-config, as we prefer having 0 projects planned (which would be suspicious enough for us to investigate) instead of having silent partial plans or projects which are suddently not skipped anymore.

**Comment by alk-jozog** [comment]
Yes I agree, I was actually surprised that Atlantis does not stop on hook failure.

**Comment by dmattia** [comment]
Sounds great. I'll close this now then and you can open an issue there if there isn't already one 👍
