### ISSUE TITLE
github branch protection rule "Status checks link" is not working

### ISSUE THREAD

**Issue by ifteehussa1n** [transcend-io/terragrunt-atlantis-config#234]
In Git PR, branch protection rule Status checks hyperlink "Details" is not working. Is there any fix availaible for this?

atlantis/plan  ......    Details
atlantis/apply  ......  Details

**Comment by dmattia** [comment]
Hey @ifteehussa1n! This is not something this library deals with, you will have better luck posting on https://github.com/runatlantis/atlantis/issues I think.
