### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by adamstrawson** [transcend-io/terragrunt-atlantis-config#276]
There hasn't been any updates since Oct 2022, and `terragrunt-atlantis-config` is showing as having a number of outdated packages with known vulnerabilities, of which 11 are high.

Some of these packages have open PRs already - https://github.com/transcend-io/terragrunt-atlantis-config/pull/271

Happy to update go.mod to address these known vulnerabilities if the PR will be actioned, but reluctant to make the effort if this project is no longer maintained.

**Comment by dmattia** [comment]
I do still accept PRs when I can, apologies for delays on any you are hoping for.
