### ISSUE TITLE
broken release

### ISSUE THREAD

**Issue by Almenon** [transcend-io/terragrunt-atlantis-config#331]
## Bug report

The release is failing. See https://github.com/transcend-io/terragrunt-atlantis-config/actions/runs/8485356520/job/23249970194
`Poetry could not find a pyproject.toml file in /github/workspace or its parents`

It looks like a bug with the action because this is not a python project so we should not expect to have a pyproject.toml file.

I opened a issue in the action's repo: https://github.com/jmgilman/actions-generate-checksum/issues/5

@dmattia FYI

**Comment by pseudomorph** [comment]
@Almenon - I've merged #332 and pushed the v.1.18.0 tag. The release was successful.

**Comment by Almenon** [comment]
The release is able to publish artifacts now 🎉
