### ISSUE TITLE
different workflow's for complex repo layout

### ISSUE THREAD

**Issue by mjagielka** [transcend-io/terragrunt-atlantis-config#39]
Hi,

I would like to know if it's possible to generate config based on 2x workflows for a specific folder's. Let's say I have two workflows: dev/prod. I would like to assign **dev** workflow for all subfolders in folder DEV and  **prod** workflow for all subfolders in folder PROD. It would be really useful option for more complex layout in git repo.

Thanks
MJ

**Comment by dmattia** [comment]
Right now this is not possible, the library only supports a single workspace across the repos, though it would be possible to add in the option for different workspace names for sure.

I will gladly work on this, but am curious why you have this restriction (why you need the different workspaces)? At Transcend, we have many different subfolders that go into many different environments in entirely separate AWS accounts, but they all are able to use the same workflow without issue.

**Comment by grimm26** [comment]
chiming in for myself with an example, we want to have a different workflow for some paths logging into the correct HasiCorp Vault instance for the correct environment for that directory so that the vault provider is connected to the correct secrets.

**Comment by dmattia** [comment]
That sounds fair. I updated the README with an example of setting a custom workflow for a project, please feel free to reopen or make a new issue if this doesn't solve your use case 😄

**Comment by mjagielka** [comment]
Thanks David ! Yes I have similar example. Different folders ( /../dev  /../prod etc) need different service accounts's which are downloaded from Google Secret Manager. Then the terragrunt can create GCP projects in these folders based on the appropriate permissions from service accounts.

**Comment by argus-github** [comment]
hcl/datasci/us-west-2/datasci/s3_buckets/sample_bucket/terragrunt.hcl

In the same sample structure above, I have a terragrunt.hcl located here :
hcl/datasci/terragrunt.hcl

It would be nice if this would not only pickup local values from this file but also apply them to the remaining nested terragrunt.hcl files such as the one at the top of this post.

**Comment by dmattia** [comment]
Feel free to pop open another issue for propagating workflow names down file trees. I have some concerns that such an approach would help people with their repos organized in a certain way, but may lead to unexpected outcomes for others.

But I'd gladly read a case for if you think it would be a good idea in general
