### ISSUE TITLE
Can't install with Go v1.10.4

### ISSUE THREAD

**Issue by mmclane** [transcend-io/terragrunt-atlantis-config#49]
I have tried to install using the command included in the documentation but it gives an error:

{16:47}~ ➭ cd && GO111MODULE=on go get github.com/transcend-io/terragrunt-atlantis-config@master && cd -                                                                 
package github.com/transcend-io/terragrunt-atlantis-config@master: invalid github.com/ import path "github.com/transcend-io/terragrunt-atlantis-config@master"

I have also tried to install with out the @master but that gave different errors:

cd && GO111MODULE=on go get github.com/transcend-io/terragrunt-atlantis-config && cd -                        <aws:prod>
package github.com/hashicorp/hcl/v2: cannot find package "github.com/hashicorp/hcl/v2" in any of:
        /usr/lib/go-1.10/src/github.com/hashicorp/hcl/v2 (from $GOROOT)
        /home/vagrant/go/src/github.com/hashicorp/hcl/v2 (from $GOPATH)
package github.com/hashicorp/hcl/v2/hclparse: cannot find package "github.com/hashicorp/hcl/v2/hclparse" in any of:
        /usr/lib/go-1.10/src/github.com/hashicorp/hcl/v2/hclparse (from $GOROOT)
        /home/vagrant/go/src/github.com/hashicorp/hcl/v2/hclparse (from $GOPATH)
package github.com/hashicorp/hcl/v2/hclwrite: cannot find package "github.com/hashicorp/hcl/v2/hclwrite" in any of:
        /usr/lib/go-1.10/src/github.com/hashicorp/hcl/v2/hclwrite (from $GOROOT)
        /home/vagrant/go/src/github.com/hashicorp/hcl/v2/hclwrite (from $GOPATH)
package github.com/hashicorp/hcl/v2/gohcl: cannot find package "github.com/hashicorp/hcl/v2/gohcl" in any of:
        /usr/lib/go-1.10/src/github.com/hashicorp/hcl/v2/gohcl (from $GOROOT)
        /home/vagrant/go/src/github.com/hashicorp/hcl/v2/gohcl (from $GOPATH)
package github.com/hashicorp/hcl/v2/hclsyntax: cannot find package "github.com/hashicorp/hcl/v2/hclsyntax" in any of:
        /usr/lib/go-1.10/src/github.com/hashicorp/hcl/v2/hclsyntax (from $GOROOT)
        /home/vagrant/go/src/github.com/hashicorp/hcl/v2/hclsyntax (from $GOPATH)

**Comment by dmattia** [comment]
Which version of go are you using?

**Comment by mmclane** [comment]
go version go1.10.4 linux/amd64

**Comment by dmattia** [comment]
Got it, that's definitely an older version. We have a test suite that ensures 1.13 and 1.14 work: https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/.circleci/config.yml#L99-L107.

This repo will typically try to stick to golangs official release system, which asks to support the two previous major releases (which would actually be v1.14 and v1.15 at this point): https://golang.org/doc/devel/release.html#policy

We can leave this issue open to tracking support for older go versions though, but in general I think homebrew may be a better fit as that version is not supported.

**Comment by mmclane** [comment]
I can verify that updating to go version 1.15 fixes the issue.

**Comment by mmclane** [comment]
Well, the install finished but then the system still couldn't find the terragrunt-atlantis-config file.  So I installed homebrew and installed it that way.  But I am still getting an error.

zsh: permission denied: terragrunt-atlantis-config

**Comment by dmattia** [comment]
Is your GOBIN in your system PATH? Here's a common configuration that might work in your bash_profile, zshrc, or other dot file:

```zsh
export GOPATH="${HOME}/.go"
export GOROOT="$(brew --prefix golang)/libexec"
export GOBIN="${GOPATH}/bin"
test -d "${GOPATH}" || mkdir "${GOPATH}"
test -d "${GOPATH}/src/github.com" || mkdir -p "${GOPATH}/src/github.com"
export PATH=$HOME/bin:/usr/local/bin:~/.tfenv/bin:$PATH:${GOBIN}:${GOROOT}/bin
```

If you have your $GOBIN in your $PATH, you should be able to run `terragrunt-atlantis-config`.

In your current setup, what is the output of `which terragrunt-atlantis-config`?

**Comment by mmclane** [comment]
OK, I was eventually able to get this to run.  Thanks for the information.

**Comment by vapomalov** [comment]
@mmclane how exactly? I have go 1.15.6 installed, added the configuration to zshrc and i still get the permission denied error.
