### ISSUE TITLE
read_terragrunt_config() will attempt to resolve `dependency` blocks

### ISSUE THREAD

**Issue by chrispblink** [transcend-io/terragrunt-atlantis-config#50]
# the problem
Hi there!  I found a fun issue when `read_terragrunt_config()` reads an hcl file with `dependency` blocks.. It will try to evaluate them as if we're doing a full-fledged `terragrunt` run

# error output
```
....
time="2020-08-25T23:18:58Z" level=info msg="Created project for /workspace/provisioning/live/aws/ACCOUNT/rds/INSTANCE_NAME/terragrunt.hcl"
time="2020-08-25T23:18:58Z" level=info msg="Created project for /workspace/provisioning/live/aws/ACCOUNT/route53/HOSTNAME/terragrunt.hcl"
time="2020-08-25T23:18:58Z" level=info msg="Created project for /workspace/provisioning/live/aws/ACCOUNT/vpc/terragrunt.hcl"
[terragrunt] [/workspace/provisioning/live/aws/ACCOUNT/elasticsearch/DOMAIN_NAME] 2020/08/25 23:18:58 Running command: terraform --version
Error: Error in function call

  on /workspace/provisioning/live/elasticsearch/ENV/DOMAIN_NAME/dashboard/DASHBOARD_NAME/terragrunt.hcl line 15, in locals:
  15:   provider_hcl = read_terragrunt_config(find_in_parent_folders("provider.hcl"))

Call to function "read_terragrunt_config" failed: exec: "terraform": executable
file not found in $PATH.

[terragrunt] 2020/08/25 23:18:58 Encountered error while evaluating locals.
```

# how to reproduce
1. Create a terragrunt config with a dependency
`provider.hcl`
```
locals {
  env = "dev"
}

# get detailed info on this elasticsearch domain
dependency elasticsearch_domain {
  config_path = "../../../aws/ACCOUNT/elasticsearch/DOMAIN_NAME"
}

# define our provider config generation
generate provider {
  path      = "elasticsearch-provider-${sha1(get_terragrunt_dir())}.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
  provider elasticsearch {
    url               = "https://${dependency.elasticsearch_domain.outputs.domain.endpoint}"
    insecure          = true
    sign_aws_requests = false
  }
  
  EOF
}
```
2. Create a terragrunt config that calls `read_terragrunt_config()` on this file
`terragrunt.hcl`
```
locals {
  # pull in repo-specific customizations
  repo_hcl = read_terragrunt_config(find_in_parent_folders("repo.hcl"))

  # pull in provider config
  provider_hcl = read_terragrunt_config(find_in_parent_folders("provider.hcl"))
}
````
3. Run `terragrunt-atlantis-config` with your favorite arguments

**Comment by dmattia** [comment]
Hello! This is actually just how Terragrunt handles the `read_terragrunt_config` function: https://github.com/gruntwork-io/terragrunt/issues/1128

It's rather annoying, and I first encountered this a number of months ago.

From that issue, yorinasub (a terragrunt mantainer) mentions that "For all intents and purposes, usage of dependency in read_terragrunt_config is broken."

At Transcend, I've removed as many dependency blocks from included terragrunt config files as I can, but I'm hopeful that eventually the function works better.

Is there anything you think that terragrunt-atlantis-config could do differently that wold help with this issue?

**Comment by chrispblink** [comment]
> This is actually just how Terragrunt handles the read_terragrunt_config function

Dang I had a feeling that was the case 😅   I'm going to use some weekend time to look into something dastardly like monkey-patching out the dependency evaluation 😈

**Comment by chrispblink** [comment]
So [monkey patching golang](https://github.com/bouk/monkey) is considered dangerous and unreliable 😅 .  I also considered some kind of auto detection & patching of `dependency` blocks but that's just too hacky.  I think the time spent implementing that would be better spent contributing to the solution of gruntwork-io/terragrunt#1128 👌
