### ISSUE TITLE
Feature Request: atlantis_terraform_version

### ISSUE THREAD

**Issue by mmclane** [transcend-io/terragrunt-atlantis-config#53]
atlantis.yaml supports an option per project to specify terraform_version.  This tool should support including this option by specifying a local.  Something like atlantis_terraform_version, similar to how atlantis_workflow is supported.

**Comment by dmattia** [comment]
This sounds great. I'm thinking:

- A flag named `--terraform-version` that sets the default across all projects
- a local named `atlantis_terraform_version` that can override that default on a per project basis

If that sounds good, I can code it up

**Comment by angeloskaltsikis** [comment]
Hello friends,
Good to see the community around this project growing and more people contributing. 🎉 
I was thinking of about the same requirement but without having to declare an extra local variable.
With a very quick look in case we add this https://github.com/gruntwork-io/terragrunt/blob/e6deff2a02cfee5c4f908157624d4b882f128bfd/config/config_partial.go#L71 to https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/cmd/generate.go#L112 we may be able to have access to the the `terraform_version_constraint` field that may be defined in a file.
I was thinking of doing it that way.
In case this field is defined in the root terragrunt file we can set it to all the projects under the root unless a terragrunt leaf file has this variable `terraform_version_constraint` defined inside it.

WDYT @dmattia  @mmclane ?
In case you like that i will be happy to contribute it.

**Comment by mmclane** [comment]
The default vault version is defined at the Atlantis server already.  I can see someone wanting to set a specific terraform version at the root and having that flow down the tree.  That isn't how I would be using it, at least not at this time but I can see that as being reasonable.  For my use case I want everything to use a specific version of tf but we occasionally have a project that gets built with the wrong version.  So, instead of going through the pain of downgrading the state file I want to be able to specify a newer version for just that project.  Being able to through that version into the terragrunt.hcl file seems easy.

At the end of the day I am not currently planning on using this tool.  I instead wrote a python script to do most of the work this was, but it allowed me to quickly add a few features that I thought we needed but were missing from your tool (this included).  But I think this utility is definitely needed and should possibly be integrated with the main atlantis tool.

**Comment by angeloskaltsikis** [comment]
Unfortunately i came across some issues with the idea i proposed above as with constraints that currently exist in Terragrunt you can get the minimum/maximum version that something can run which is not sufficient for what we need.
Any other ideas for the implementation are appreciated. 
I haven't pushed my code yet as it is not even close to be considered usable.
cc. @dmattia

**Comment by dmattia** [comment]
There's always running the code equivalent of `terragrunt state pull | jq ".terraform_version"`, but I don't love the idea of relying on the state having a specific format because there aren't any guarantees over its structure that I can tell.

This is more of a general community question, but how often do people change their terraform versions between modules?

If it's not terribly often, I don't think the `locals` approach is a bad idea.
