### ISSUE TITLE
Handle extra_arguments variable files

### ISSUE THREAD

**Issue by dmattia** [transcend-io/terragrunt-atlantis-config#60]
https://terragrunt.gruntwork.io/docs/features/keep-your-cli-flags-dry/#required-and-optional-var-files

Original mention came from https://github.com/transcend-io/terragrunt-atlantis-config/issues/59

**Comment by dmattia** [comment]
Released in https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v0.9.2

**Comment by ryan-dyer-sp** [comment]
David, we dont actually use either required or optional var files as they didnt exist when I started using terragrunt (a few years now).  We use the arguments option eg: 
```
 extra_arguments "common_var" {
    arguments = [
      "-var-file=${get_terragrunt_dir()}/../../../../common_vars/apps/consul/sg.tfvars",
      "-var-file=${get_terragrunt_dir()}/main.tfvars"
    ]
  }
```

**Comment by dmattia** [comment]
ah gotcha that makes sense. Release v0.9.4 (https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v0.9.4) adds support for `-var-file=` arguments.

I wasn't able to get your exact example working, as I believe the `commands` field is required under extra_arguments. I'm guessing that was just a simplification from your copy-paste though?

Thank you for guinea pigging this @ryan-dyer-sp, please let me know if this now runs for you

**Comment by ryan-dyer-sp** [comment]
Yes sorry, the commands section was stripped.    For us we use:
```
commands = [for c in get_terraform_commands_that_need_vars() : c if c != "apply"]
```  
This prevents anyone from just running terragrunt apply.  We insist that all applies be done with a plan file.

I just tried updating from master, and it doesnt appear to be pulling a 0.9.4.

**Comment by ryan-dyer-sp** [comment]
Was able to pull down the 0.9.4 and it does work for properly handling the extra_arguments, Thanks!

However I can't seem to get the atlantis_extra_dependencies in the top level terragrunt.hcl to work.  In our top level terragrunt I have:
```
locals {
  current_dir    = get_terragrunt_dir()
  root_dir       = run_cmd("--terragrunt-quiet", "bash", "-c", "dirname $(dirname ${get_parent_terragrunt_dir()}) | tr -d '\n'")
  provider_dir   = run_cmd("--terragrunt-quiet", "bash", "-c", "echo ${local.current_dir} | sed 's|${local.root_dir}||g' | tr -d '\n'") # Appened a 'tr' invocation to remove a trailing newline which is added by the sed version which comes standard on a Mac (BSD).
  overwrite_tags = { "created_by" : "terragrunt${local.provider_dir}" }

  common_tags      = yamldecode(fileexists("${find_in_parent_folders("../common_vars/common_tags.yaml", "nonexistant")}") ? file("${find_in_parent_folders("../common_vars/common_tags.yaml")}") : "{}")
  environment_tags = yamldecode(fileexists("${find_in_parent_folders("environment_tags.yaml", "nonexistant")}") ? file("${find_in_parent_folders("environment_tags.yaml")}") : "{}")
  regional_tags    = yamldecode(fileexists("${find_in_parent_folders("region_tags.yaml", "nonexistant")}") ? file("${find_in_parent_folders("region_tags.yaml")}") : "{}")
  application_tags = yamldecode(fileexists("${find_in_parent_folders("application_tags.yaml", "nonexistant")}") ? file("${find_in_parent_folders("application_tags.yaml")}") : "{}")
  instance_tags    = yamldecode(fileexists("${find_in_parent_folders("instance_tags.yaml", "nonexistant")}") ? file("${find_in_parent_folders("instance_tags.yaml")}") : "{}")
  local_tags       = yamldecode(fileexists("${path_relative_to_include()}/local_tags.yaml") ? file("${path_relative_to_include()}/local_tags.yaml") : "{}")

  environment_vars = read_terragrunt_config(find_in_parent_folders("environment.hcl", "nonexistant"), { locals = {} })
  region_vars      = read_terragrunt_config(find_in_parent_folders("region.hcl", "nonexistant"), { locals = {} })
  application_vars = read_terragrunt_config(find_in_parent_folders("application.hcl", "nonexistant"), { locals = {} })

  extra_atlantis_dependencies = [
    "foo",
    fileexists("${find_in_parent_folders("../common_vars/common_tags.yaml")}")
  ]
}
```
If I drop the fileexists line of the e_a_d, I see foo for all the projects that this t.hcl is the parent.  However with it, I see neither foo or the path to common_tags.yaml.

As you can see, all of these files are optional; though in most cases they do exist.  I dont really see a way to handle this via the extra_a_d.  I tried an empty string 
```
[ "foo", "", "bar" ]
```
And the "" gets converted to a . in the dependency list.  If there isnt a way, could you add support for a NULL, None, -, <whatever> string, where if the evaluation returns that, you drop it from the list?

**Comment by ryan-dyer-sp** [comment]
Was able to pull down the 0.9.4 and it does work for properly handling the extra_arguments, Thanks!

However I can't seem to get the atlantis_extra_dependencies in the top level terragrunt.hcl to work.  In our top level terragrunt I have:
```
locals {
  current_dir    = get_terragrunt_dir()
  root_dir       = run_cmd("--terragrunt-quiet", "bash", "-c", "dirname $(dirname ${get_parent_terragrunt_dir()}) | tr -d '\n'")
  provider_dir   = run_cmd("--terragrunt-quiet", "bash", "-c", "echo ${local.current_dir} | sed 's|${local.root_dir}||g' | tr -d '\n'") # Appened a 'tr' invocation to remove a trailing newline which is added by the sed version which comes standard on a Mac (BSD).
  overwrite_tags = { "created_by" : "terragrunt${local.provider_dir}" }

  common_tags      = yamldecode(fileexists("${find_in_parent_folders("../common_vars/common_tags.yaml", "nonexistant")}") ? file("${find_in_parent_folders("../common_vars/common_tags.yaml")}") : "{}")
  environment_tags = yamldecode(fileexists("${find_in_parent_folders("environment_tags.yaml", "nonexistant")}") ? file("${find_in_parent_folders("environment_tags.yaml")}") : "{}")
  regional_tags    = yamldecode(fileexists("${find_in_parent_folders("region_tags.yaml", "nonexistant")}") ? file("${find_in_parent_folders("region_tags.yaml")}") : "{}")
  application_tags = yamldecode(fileexists("${find_in_parent_folders("application_tags.yaml", "nonexistant")}") ? file("${find_in_parent_folders("application_tags.yaml")}") : "{}")
  instance_tags    = yamldecode(fileexists("${find_in_parent_folders("instance_tags.yaml", "nonexistant")}") ? file("${find_in_parent_folders("instance_tags.yaml")}") : "{}")
  local_tags       = yamldecode(fileexists("${path_relative_to_include()}/local_tags.yaml") ? file("${path_relative_to_include()}/local_tags.yaml") : "{}")

  environment_vars = read_terragrunt_config(find_in_parent_folders("environment.hcl", "nonexistant"), { locals = {} })
  region_vars      = read_terragrunt_config(find_in_parent_folders("region.hcl", "nonexistant"), { locals = {} })
  application_vars = read_terragrunt_config(find_in_parent_folders("application.hcl", "nonexistant"), { locals = {} })

  extra_atlantis_dependencies = [
    "foo",
    find_in_parent_folders("../common_vars/common_tags.yaml")
  ]
}
```
If I drop the fileexists line of the e_a_d, I see foo for all the projects that this t.hcl is the parent.  However with it, I see neither foo or the path to common_tags.yaml.

As you can see, all of these files are optional; though in most cases they do exist.  I dont really see a way to handle this via the extra_a_d.  I tried an empty string 
```
[ "foo", "", "bar" ]
```
And the "" gets converted to a . in the dependency list.  If there isnt a way, could you add support for a NULL, None, -, <whatever> string, where if the evaluation returns that, you drop it from the list?

**Comment by ryan-dyer-sp** [comment]
and additional info, if I take the e_a_d block and put it in a child t.hcl, I get the expected results.  Seems there's potentially an issue with how functions are getting ran/parsed(?) when in the parent.

**Comment by dmattia** [comment]
This is great feedback, I have some ideas of what's going on, but I think there's an important question here: When you write `find_in_parent_folders("../common_vars/common_tags.yaml")`, do you intend for that to be relative to the parent, or to the child?

Right now, I have it set up to be relative to the parent, but I can quickly PR a change that would make it so that it is relative to the child (which I think makes more sense). I'll probs add quite a few docs for this as it's a bit confusing right now, so I'm interested in knowing what your thoughts are.

**Comment by dmattia** [comment]
Right now it is ambiguous if a parent having `extra_atlantis_dependencies = ["foo.json"]` means that there is a a `foo.json` file in the same directory as the parent, or if all child modules inheriting from that parent will depend on a file named `foo.json` in their directory.

I'll need to make this behavior consistent and make the docs clearer for sure

**Comment by ryan-dyer-sp** [comment]
> This is great feedback, I have some ideas of what's going on, but I think there's an important question here: When you write `find_in_parent_folders("../common_vars/common_tags.yaml")`, do you intend for that to be relative to the parent, or to the child?
> 
> Right now, I have it set up to be relative to the parent, but I can quickly PR a change that would make it so that it is relative to the child (which I think makes more sense). I'll probs add quite a few docs for this as it's a bit confusing right now, so I'm interested in knowing what your thoughts are.

The directory happens to be relative to the parent terragrunt.  However, for the purpose of the function, it doesnt matter.  It starts with the child directory and looks for the file.  If it doesnt find it, it simply keeps moving up the parent and trying again.  For my example, you can swap '../common_vars' for ./common_vars' and the result is still the same. You can even put in a full path relative to / and it will find it if its there.  If someone were to create a common_vars/common_tags.yaml file up X levels from the child but lower than the parent, it would find that one instead of the one which is up from the parent.

> Right now it is ambiguous if a parent having extra_atlantis_dependencies = ["foo.json"] means that there is a a foo.json file in the same directory as the parent, or if all child modules inheriting from that parent will depend on a file named foo.json in their directory.

m2c for this use case would be that its relative to the child.  Specifying a file like this isnt something we would ever do to begin with.  Any file references we have in terragrunt or even in terraform all have relative paths (even if its just './') and the relation is always from the directory where the child t.hcl lives (or from where the cache is going to install all the tf code in the case of tf module references)

**Comment by dmattia** [comment]
That all makes sense!

I have released v0.9.5: https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v0.9.5

I also updated the documentation to explain the new functionality of parent dependencies with explicit rules: https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v0.9.5

I believe my example under https://github.com/transcend-io/terragrunt-atlantis-config/tree/master/test_examples/parent_with_extra_deps is similar to your use case, and is tested here: https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/cmd/generate_test.go#L183-L189 to confirm that it produces this output: https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/cmd/golden/mergeParentDependencies.yaml

Please let me know as always if you have any troubles :)

**Comment by ryan-dyer-sp** [comment]
Tested looks great!  The only thing outstanding I can see, is how to handle the use case where the file doesnt exist. ie
```
 extra_atlantis_dependencies = [
    find_in_parent_folders("../common_vars/common_tags.yaml"),
    find_in_parent_folders("environment_tags.yaml"),
    find_in_parent_folders("instance_tags.yaml", "")
  ]
```
The first two should always be present, but the instance_tags is entirely optional.  Currently this results in a '.' being placed in the autoplan file list.  Any thoughts toward dropping it from the list?


Thanks!

**Comment by dmattia** [comment]
Awesome, v0.9.6 should allow you to ignore empty strings: https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v0.9.6

**Comment by ryan-dyer-sp** [comment]
Fantastic.

Ok last thing.  We have the local_tags which uses a different function.  This doesnt appear to work.  local_tags.yaml is always placed in the child directory.  But it's optional.  I tried the function as shown in example in earlier post as well as a  basic fileexists("local_tags.yaml") ? "./local_tags.yaml" : ""  But it never came up with anything.  Thoughts?

**Comment by dmattia** [comment]
I added in a working test that covers that use case in release v0.9.7: https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v0.9.7

Here's the line of the updated test in question: https://github.com/transcend-io/terragrunt-atlantis-config/pull/73/files#diff-5be4a163ad2514a1736f81a180ba3bd8R7

Unfortunately, I believe terragrunt (whose parser I use under the hood in this lib) will always evaluate Terraform functions (like fileexists) from the directory of the parent, not from the child module like Terragrunt functions (like `find_in_parent_folders`).

Because of this, you'll notice that my line looks like `fileexists("${path_relative_to_include()}/local_tags.yaml") ? "local_tags.yaml" : "",`. By using a Terragrunt function (path_relative_to_include), you can ensure that the `fileexists` function is checking the right file. Hopefully that isn't to gross of a solution for you right now, while I'll follow up with Terragrunt to chat about their Terraform function contexts soon.

**Comment by ryan-dyer-sp** [comment]
That's what I had, but guess I didnt notice you released 0.9.7.  All is great!  Thanks for all your hard work and quick responses to these requests.  

One final question.  How do you envision this being used?  As mentioned previously, we have a mono repo where ops and devs can contibute changes.  Currently when people add new code, they're expected to add the corresponding atlantis.yaml entries.

Do you think users should run this as an easy way to add the entries and then commit the change as part of their PRs or do you see some sort of build/CI process which handles this?

**Comment by dmattia** [comment]
Great question!

In the long term, I hope to integrate this more into Atlantis. There are a few discussions around this already:
- https://github.com/runatlantis/atlantis/issues/1183
- https://github.com/runatlantis/atlantis/issues/500

In particular, issue 500 on atlantis talks about server side hooks that would allow this tool to generate config entirely on the server side. This way, devs wouldn't even need to know that atlantis.yaml files exist.

But for now, the file needs to be in the repo, so we can't use that solution yet. But here's what I do at Transcend (where we also have a monorepo):

1. I have an alias in a common .bash_profile file that allows anyone to quickly update the config: `alias infra:update="FAST_MODE=true terragrunt-atlantis-config generate --output ~/transcend/main/atlantis.yaml --root ~/transcend/main --autoplan --parallel --create-workspace"`
2. We have a Github action set up that will check on any PR to ensure that the atlantis.yaml is up to date. See this link in the README for some context on how to do this: https://github.com/transcend-io/terragrunt-atlantis-config#auto-enforcement-with-github-actions

We've had really good success with this setup with having ops + devs be able to make changes. If someone who hasn't worked on infra before opens a PR with some new directory, the github status will show a failure, and a reviewer can politely ask them to run `infra:update` and push up a new commit (which will make the status pass, but is also necessary so that atlantis picks up that it should run on the new directory).

**Comment by ryan-dyer-sp** [comment]
Would be great if this tool does get baked into atlantis itself.  

What is FAST_MODE=true ?

We use bitbucket... :(  but I may be able to come up with a pipeline build which does the same validation and force the PR to require that successful build the same way we require successful plans and applies before merging. 

Thanks for the excellent info and suggestions!

**Comment by dmattia** [comment]
`FAST_MODE` isn't really related to this tool, but in our Terragrunt configs we use it in some places that use `run_cmd` from Terragrunt so that when `FAST_MODE` is true, the cmd does a noop. This is because `terragrunt-atlantis-config` often doesn't care about actually running the commands, which can take some time (like fetching secrets from Hashicorp Vault).

As an example:

```hcl
locals {
  normal_args = [
    "--terragrunt-quiet",
    "node",
    "signRequest.js",
    "arn:aws:iam::1234567:role/Some-Role-That-Auths-To-Vault"
  ]

  fastmode_args = ["echo", "skipping all commands"]
  is_fastmode = tobool(get_env("FAST_MODE", "false"))

  cmd_args = local.is_fastmode ? local.fastmode_args : local.normal_args
}

inputs = {
  request_headers = run_cmd(local.cmd_args...)
}
```

If you have a large monorepo, that may be useful to you (or become useful at some point) if `terragrunt-atlantis-config` takes too long to run. With that optimization in a few places, we can generate a config for 500 modules in under a second on CI (though locally it takes 15ish seconds still).

And if you use bitbucket, you may benefit from seeing how I used to validate on CircleCI:

```yaml
validate-atlantis-yaml:
    executor: ci-base-go
    steps:
      - git-shallow-clone/checkout
      - run: FAST_MODE=true terragrunt-atlantis-config generate --output atlantis.yaml.expected --autoplan --parallel=false
      - run: diff atlantis.yaml atlantis.yaml.expected
      - run:
          name: Explain Fix
          command: echo "To fix the issue here, try running `infra:update` locally and pushing up the changes"
          when: on_fail
      - transcend/notify_slack_on_failure
```

Honestly I liked that config more than the current Github Action, but for most users the Github Action is a bit more baked-in for them to use.

**Comment by jmreicha** [comment]
I know this is old, I am wondering how `FAST_MODE` is configured. I have the exact use case where I don't want to run these commands when generating the config but can't seem to find anything elsewhere about how to skip them.
