### ISSUE TITLE
How to propose a Homebrew release

### ISSUE THREAD

**Issue by chrispblink** [transcend-io/terragrunt-atlantis-config#7]
Hi there,

First things first _thank you **so much**_ for creating this tool!  Even for our small repos this is such a huge quality-of-life improvement 🤩 

Alrighty, so, how do I propose a new Homebrew release?  I looked around this repo and [transcend-io/homebrew-tap](https://github.com/transcend-io/homebrew-tap) but I couldn't quite figure out how builds happen 🤔 

Thanks!

**Comment by dmattia** [comment]
Excellent question!

I just went ahead and added this repo to CircleCI. On non-master branches, PRs will build the binary to ensure there are no compile errors.

On merges to master, that build will be pushed to an S3 bucket we own (publically readable, only we can push to it).

So once your future PRs are merged to `master`, you can make a PR similar to https://github.com/transcend-io/homebrew-tap/pull/1/files and we can approve the release.

Thanks for your contributions so far! We went ahead and released v0.0.5 with all your recent updates.
