### ISSUE TITLE
Problem installing with homebrew - sha mismatch

### ISSUE THREAD

**Issue by tomasbackman** [transcend-io/terragrunt-atlantis-config#83]
This happened today and a few days ago as well:

Running:
`brew install transcend-io/tap/terragrunt-atlantis-config`
Gives:
`==> Installing terragrunt-atlantis-config from transcend-io/tap
==> Downloading https://homebrew.transcend.io/terragrunt-atlantis-config/0.9.7/terragrunt-atlantis-config_0.9.7_darwin_amd64.zip
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 967761ddc1516baf0d308708d25c57b7e7743e5e1c160c5abd92abe03427bda3
  Actual: 3a8a0edefb7ea553ad2ecc1a199a1b875be8027f928c23f822ed82ce970a9a4d`

Also when I install the recommended way (`cd && GO111MODULE=on go get github.com/transcend-io/terragrunt-atlantis-config@v0.10.1 && cd -`) the package is installed (I can find it under GOPATH) but I cannot run the command `terragrunt-atlantis-config`so  I guess the command need to be made accesible or built or something.. so some more instructions/tips in README would be nice as well =)

**Comment by tomasbackman** [comment]
I got the one I installed with `go get` working when I found the `terragrunt-atlantis-config` command in the go/bin directory. So that is fixed. But the brew version still need fixing.

**Comment by dmattia** [comment]
Thanks for the Issue!

I believe brew should now be fixed after merging in https://github.com/transcend-io/homebrew-tap/pull/14
