### ISSUE TITLE
Support setting autoplan via local variable

### ISSUE THREAD

**Issue by jghward** [transcend-io/terragrunt-atlantis-config#84]
Similar to https://github.com/transcend-io/terragrunt-atlantis-config/issues/53 - I have many projects which use the same workflow, but I wish to disable `autoplan` on some of them.

It would be super useful if I could set a local variable called `atlantis_autoplan` to `true` or `false` in my projects `terragrunt.hcl` file.

In general, it would be great if any flag could be set by a local `atlantis_${flag}` var.

**Comment by dmattia** [comment]
I think this is a great idea. I'll prioritize this first when I have some time, as I think this feature will be easy enough to do and should be quite helpful for others
