### ISSUE TITLE
with terragrunt-alantis-config, do i still need to commit the alantis.yaml to github ?

### ISSUE THREAD

**Issue by IamGabrielWu** [transcend-io/terragrunt-atlantis-config#86]
I don't know how to make the atlantis.yaml automatically generated every time i create a pull request, and atlantis can pick up this auto generated file then do terragrunt plan or apply. 

I think this would be best if atlantis.yaml can be auto generated and i don't need to keep track of this file in github repo.

**Comment by michaelfarrell76** [comment]
the plan for this is atlantis is adding a feature to allow for pre-workflow custom hooks

[see the issue](https://github.com/runatlantis/atlantis/issues/500)
[and the open pr](https://github.com/runatlantis/atlantis/pull/1255)

**Comment by michaelfarrell76** [comment]
for now would recommend committing the atlantis.yaml until that is merged

**Comment by IamGabrielWu** [comment]
I'm looking at ["terragrunt-atlantis-config using github action to validate atlantis.yaml"](https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/README.md#auto-enforcement-with-github-actions) . I'm not sure it's a way to achieve what i need. @michaelfarrell76

**Comment by angeloskaltsikis** [comment]
@IamGabrielWu You can follow the method described in this [medium post](https://build.thebeat.co/ci-cd-for-terragrunt-iac-through-atlantis-9e7ba98ac487) till the PR of having pre-workflow custom hooks is merged.

I would advise against committing as you will have each user run the current project
cc. @michaelfarrell76

**Comment by dmattia** [comment]
I'm going to close this, but feel free to open if you have any other questions.

To summarize:
- you can keep committing atlantis.yaml to github
- @angeloskaltsikis has a very nice solution you can migrate to now to not need to commit
- fairly soon, atlantis should support hooks that are another option for not needing to commit

**Comment by dmattia** [comment]
https://github.com/runatlantis/atlantis/pull/1255 has been released in Atlantis v0.16.0, allowing us to run terragrunt-atlantis-config on the Atlantis server side of things.

I'll be updating the documentation of this repo soon with how to use the new features 😄

**Comment by tsunamishaun** [comment]
@angeloskaltsikis the post wasn't entirely clear on how to setup the post-clone git hook, I ended up putting the core.hooksPath in /etc/gitconfig with /home/atlantis/hooks as the path. Though I am using the new pre-workflow feature of atlantis it doesn't consistently run for subsequent workspaces, making my atlantis.yaml not clone into each workspace directory. I am using both methods now and things appear stable, would love to keep the conversation going and see what you come up with @dmattia.

**Comment by kitos9112** [comment]
Many thanks @tsunamishaun for sharing the above code snippet. It has just solved the first impediment I was facing with this fantastic tool to generate the `atlantis.yaml` - Although, I slightly modified the Terraform built-in function as I didn't bother about hardcoding the name of my AWS workload in the top-level `terragrunt.hcl`:

```hcl
locals {
  (...)
  atlantis_skip = contains(["dev"], local.aws_account_workload) ? false : true
}
```
At the moment, we only let Atlantis run in our AWS development account so we can take careful decisions about moving code into other more sensitive environments by leveraging a dedicated GitLab runner.

I even think it should be clearly indicated in the README.md of this project given the fact it also works despite utilising the CLI flag `--ignore-parent-terragrunt`:

_How to limit the automatic generation of an `atlantis.yaml` configuration for a well-known Terragrunt directory-driven layout:_

``` bash
account
 └ _global
 └ region
    └ _global
    └ environment
       └ resource
```
