### ISSUE TITLE
Set --ignore-parent-terragrunt as true by default

### ISSUE THREAD

**Issue by devlincashman** [transcend-io/terragrunt-atlantis-config#95]
In most cases it seems like you would want to have this flag set to true as otherwise you will receive an error if you are basing your terragrunt design on the terragrunt infrastructure examples:

https://github.com/gruntwork-io/terragrunt-infrastructure-live-example

The documentation included suggests as much in the argument reference. However since it's not turned on by default less observant people (like me) might struggle for a while before figuring out what they need to change :).

I'd recommend having it on by default and maybe making a note of it in the usage section.

**Comment by dmattia** [comment]
I've been thinking about it, and I think it's a good idea to make the default `true`.

It'll have to come in a major release, but I am planning on one very soon anyways.
